apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-node
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: blockchain-node
  template:
    metadata:
      labels:
        app: blockchain-node
    spec:
      containers:
        - name: blockchain-node
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }} # Use Dockerfile.hardhat build image
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
      restartPolicy: Always
