services:
  blockchain-node:
    build:
      context: .
      dockerfile: Dockerfile.hardhat
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://blockchain-node:8545"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - JSON_RPC_URL=http://blockchain-node:8545/

  blockchain-tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      blockchain-node:
        condition: service_healthy
    env_file:
      - .env

  blockchain-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - JSON_RPC_URL=http://blockchain-node:8545/
    depends_on:
      blockchain-node:
        condition: service_healthy
    env_file:
      - .env
