version: '3.8'

services:
  blockchain-node:
    build:
      context: .
      dockerfile: Dockerfile.hardhat
    ports:
      - "8545:8545"
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 5
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
    volumes:
      - .:/usr/src/app
    depends_on:
      blockchain-node:
        condition: service_healthy
    environment:
      - JSON_RPC_URL=http://blockchain-node:8545/
      - CONTRACT_ADDRESS=0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44