# Use the official Node.js image as a base image
FROM node:20-alpine

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY hardhat.config.js .
COPY ./test ./test
COPY ./contracts ./contracts

# Run the Hardhat node
CMD ["npx", "hardhat", "test"]