# Use the official Node.js image as a base image
FROM node:20

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 8545 for the JSON-RPC connection
EXPOSE 8545

# Run the Hardhat node
ENTRYPOINT [ "scripts/entrypoint.sh" ]
