apiVersion: v1
kind: Secret
metadata:
  name: pysyft
type: Opaque
stringData:
  rootPassword:
---
apiVersion: v1
kind: Secret
metadata:
  name: guehds
type: Opaque
stringData:
  fusionauth_client_secret: 
  fusionauth_api_key: 
  POSTGRES_PASSWORD: 
  DATABASE_URL: