apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
  labels:
    app.kubernetes.io/component: ingress
    app.kubernetes.io/instance: trustchain
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: syft
  name: syft-ingress
spec:
  ingressClassName: tailscale
  rules:
  - http:
      paths:
      - backend:
          service:
            name: proxy
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - syft-sde-chuc
