apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-blockchain-node
spec:
  selector:
    app: blockchain-node
  ports:
  - port: {{ .Values.blockchainNode.port }}
    targetPort: {{ .Values.blockchainNode.port }}