[tool.poetry]
name = "fedtest"
version = "0.1.0"
description = ""
authors = ["António Bezerra <antonio.bezerra@promptlyhealth.com>"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
syft = {version = "0.8.6", extras = ["datascience"]}
ipykernel = "^6.29.3"
streamlit = "^1.33.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
