apiVersion: v2
version: 0.0.1
name: trustchain
type: application

dependencies:
  - name: syft
    version: 0.8.6
    repository: https://openmined.github.io/PySyft/helm
  - name: guehds
    version: 0.1.0
  - name: blockchain-api
    version: 0.1.0
