replicaCount: 1

image:
  repository: didioffside/api-guedhs
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 32000
  # Optional: Specify a static port, or Kubernetes will assign one

env:
  - name: JSON_RPC_URL
    value: "http://blockchain-node-service:8545"
  - name: PRIVATE_KEY
    value: "df57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e"
  - name: CONTRACT_ADDRESS
    value: "0x73511669fd4dE447feD18BB79bAFeAC93aB7F31f"
  - name: PORT
    value: "3000"
#  - name: PORT
 #   value: "3000"
resources: {}
